# Generated by Django 2.1.7 on 2019-02-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='titile',
            new_name='title',
        ),
    ]
